### ISSUE TITLE
CosmeticsCore doesn't work on 1.19.3

### ISSUE THREAD

**Issue by Jackboittv** [PluginBugs/Issues-CosmeticsCore#72]
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Jackboi#0155

### What happened?

I keep getting the same error, and my server is in a constant loop of shutting down and starting. This is the only error I can't fix, as there's no newer version of CosmeticsCore

### Steps to reproduce the issue

1. Have the same plugins as me
2. Update all plugins
3. Update server from 1.19.2 -> 1.19.3

### Server version

This server is running Purpur version git-Purpur-1876 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4a580c4 on HEAD)

### CosmeticsCore Version

Cosmeticscore 1.0.5

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs v1.0.22

### FULL server log

[16:03:20 INFO]: [ItemsAdder] Enabling ItemsAdder v3.3.0b-r2
[16:03:20 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R2! Trying to find NMS support
[16:03:20 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_19_R2) is not supported by this NBT-API Version(2.10.0) located at dev.lone.LoneLibs.nbt.nbtapi.utils.MinecraftVersion. The NBT-API will try to work as good as it can! Some functions may not work!
[16:03:20 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[16:03:20 INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.3.0b-r2
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.22
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-1876 (MC: 1.19.3)
                                               
[16:03:20 INFO]: [ItemsAdder] LightAPI not installed, please install it to see blocks emitting light: https://a.devs.beer/lightapi-new
[16:03:21 INFO]: [ItemsAdder] Registered Citizens NPC Trait: customentity
[16:03:21 INFO]: [Spartan] Enabling Spartan vPhase 490
[16:03:22 INFO]: [QuickShop] Registering Spartan Compatibility Module
[16:03:22 INFO]: [Quests] Enabling Quests v4.6.1-b373
[16:03:22 INFO]: [Quests] Loaded language en-US. Translations via Crowdin
[16:03:22 INFO]: [Quests] Successfully linked Quests with Citizens 2.0.30-SNAPSHOT (build 2846)
[16:03:22 INFO]: [Quests] Loading storage implementation: YAML
[16:03:22 INFO]: [Spartan Notification] Done loading 103 rows of data to the Research Engine.
[16:03:22 INFO]: [Duels] Enabling Duels v3.5.2
[16:03:22 INFO]: [Duels] Successfully hooked into 'Essentials'!
[16:03:22 INFO]: [Duels] Successfully hooked into 'mcMMO'!
[16:03:22 INFO]: [PlaceholderAPI] Successfully registered expansion: duels [1.0]
[16:03:22 INFO]: [Duels] Successfully hooked into 'PlaceholderAPI'!
[16:03:22 INFO]: [Duels] Using Economy Provider: com.earth2me.essentials.economy.vault.VaultEconomyProvider
[16:03:22 INFO]: [Duels] Successfully hooked into 'Vault'!
[16:03:22 INFO]: [Duels] Successfully hooked into 'WorldGuard'!
[16:03:22 INFO]: [Duels] KitManagerImpl: Loaded 1 kit(s).
[16:03:22 INFO]: [Duels] ArenaManagerImpl: Loaded 2 arena(s).
[16:03:22 INFO]: [Duels] QueueManager: Loaded 2 queue(s).
[16:03:22 INFO]: [Duels] QueueSignManagerImpl: Loaded 1 queue sign(s).
[16:03:22 INFO]: [PlaceholderAPI] Successfully registered expansion: duels [1.0.0]
[16:03:22 INFO]: [Duels] ExtensionManager: Extension 'Placeholders 1.0.4' is now enabled.
[16:03:22 INFO]: [GSit] Enabling GSit v1.3.0
[16:03:22 INFO]: [GSit] The plugin was successfully enabled.
[16:03:22 INFO]: [GSit] Link with WorldGuard successful!
[16:03:22 INFO]: [GSit] Link with PlaceholderAPI successful!
[16:03:22 INFO]: [PlaceholderAPI] Successfully registered expansion: gsit [1.3.0]
[16:03:22 INFO]: [GSit] Link with GriefPrevention successful!
[16:03:22 INFO]: [MarriageMaster] Enabling MarriageMaster v2.6.8-Release
[16:03:22 INFO]: [MarriageMaster] Starting Marriage Master in standalone mode!
[16:03:22 INFO]: [MarriageMaster] Config file successfully loaded.
[16:03:22 INFO]: [MarriageMaster] No compatible backpack plugin found.
[16:03:22 INFO]: [MarriageMaster] Language file successfully loaded. Language: English  Author: GeorgH93
[16:03:22 INFO]: [at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.HikariDataSource] MarriageMaster-Connection-Pool - Starting...
[16:03:22 INFO]: [at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.HikariDataSource] MarriageMaster-Connection-Pool - Start completed.
[16:03:22 INFO]: [MarriageMaster] Loading marriages ...
[16:03:22 INFO]: [MarriageMaster] Marriages loaded
[16:03:22 INFO]: [MarriageMaster] Loading priests ...
[16:03:22 INFO]: [MarriageMaster] Priests loaded
[16:03:22 INFO]: [MarriageMaster] Loading players ...
[16:03:22 INFO]: [MarriageMaster] Players loaded
[16:03:22 INFO]: [MarriageMaster] Writing marriages into cache ...
[16:03:22 INFO]: [MarriageMaster] Marriages loaded into cache
[16:03:22 INFO]: [MarriageMaster] Loading homes ...
[16:03:22 INFO]: [MarriageMaster] Homes loaded
[16:03:22 INFO]: [MarriageMaster] Item name language file successfully loaded. Language: english  Author: GeorgH93
[16:03:22 INFO]: [MarriageMaster] Loading item translations ...
[16:03:22 INFO]: [MarriageMaster] Finished loading item translations for 828 items.
[16:03:23 INFO]: [PlaceholderAPI] Successfully registered expansion: marriagemaster [2.6.8-Release]
[16:03:23 INFO]: [MarriageMaster] PlaceholderAPI hook was successfully registered!
[16:03:23 INFO]: [MarriageMaster]  Marriage Master has been enabled!  :) 
[16:03:23 INFO]: [CMILib] Enabling CMILib v1.2.4.1
[16:03:24 INFO]: Server version: v1_19_R2 - 1.19.3 - paper
[16:03:24 INFO]: [PlaceholderAPI] Successfully registered expansion: cmil [1.2.4.1]
[16:03:24 INFO]: PlaceholderAPI hooked.
[16:03:24 INFO]: Updated (EN) language file. Took 21ms
[16:03:24 INFO]: [Jobs] Enabling Jobs v5.1.1.1
[16:03:24 INFO]: ------------- Jobs -------------
[16:03:24 INFO]: [PlaceholderAPI] Successfully registered expansion: jobsr [5.1.1.1]
[16:03:24 INFO]: PlaceholderAPI hooked.
[16:03:24 INFO]: Connected to database (SqLite)
[16:03:24 INFO]: Loaded 8 titles
[16:03:24 INFO]: Loaded 69 protected blocks timers
[16:03:24 INFO]: Loaded 1282 custom item names
[16:03:24 INFO]: Loaded 79 custom entity names
[16:03:24 INFO]: Loaded 2 custom MythicMobs names
[16:03:24 INFO]: Loaded 38 custom enchant names
[16:03:24 INFO]: Loaded 21 custom enchant names
[16:03:24 INFO]: Loaded 16 custom color names
[16:03:24 INFO]: Loaded 4 shop items
[16:03:24 INFO]: Loaded 1 quests for Fisherman
[16:03:24 INFO]: Loaded 1 quests for Woodcutter
[16:03:24 INFO]: Loaded 1 quests for Builder
[16:03:24 INFO]: Loaded 1 quests for Digger
[16:03:24 INFO]: Loaded 1 quests for Miner
[16:03:24 INFO]: Loaded 1 quests for Enchanter
[16:03:24 INFO]: Loaded 1 quests for Farmer
[16:03:24 INFO]: Loaded 1 quests for Weaponsmith
[16:03:24 INFO]: Loaded 1 quests for Explorer
[16:03:24 INFO]: Loaded 1 quests for Crafter
[16:03:24 INFO]: Loaded 1 quests for Hunter
[16:03:24 INFO]: Loaded 1 quests for Brewer
[16:03:24 INFO]: Loaded 12 jobs
[16:03:24 INFO]: Loaded 0 boosted items
[16:03:25 INFO]: Started buffered payment thread.
[16:03:25 INFO]: Started database save task.
[16:03:25 INFO]: Preloaded 3 players data in 0.0
[16:03:25 INFO]: WorldGuard detected.
[16:03:25 INFO]: mcMMO2.1.217 was found - Enabling capabilities.
[16:03:25 INFO]: Registered McMMO 2.x listener
[16:03:25 INFO]: Loading explorer data
[16:03:25 INFO]: Loaded explorer data (9) in 1 ms
[16:03:25 INFO]: Plugin has been enabled successfully.
[16:03:25 INFO]: ------------------------------------
[16:03:25 INFO]: [CrateReloaded] Enabling CrateReloaded v2.1.14
[16:03:25 INFO]: [CrateReloaded] Plugin is not enabled: HolographicDisplays
[16:03:25 INFO]: [CrateReloaded] Provider: Vault
[16:03:25 INFO]: [CrateReloaded] Provider: EffectLib
[16:03:25 INFO]: [CrateReloaded] Crate Configurations (1): crate.yml 
[16:03:25 INFO]: [CosmeticsCore] Enabling CosmeticsCore v1.0.5
[16:03:25 ERROR]: [CosmeticsCore] Error getting implementation for class dev.lone.cosmeticscore.nms.aH.aN - NMS v1_19_R2
[16:03:25 WARN]: java.lang.ClassNotFoundException: dev.lone.cosmeticscore.nms.aH.impl.v1_19_R2
[16:03:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179)
[16:03:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126)
[16:03:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:03:25 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:03:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[16:03:25 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.main.ah.a(SourceFile:126)
[16:03:25 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.nms.aH.aN.<init>(SourceFile:29)
[16:03:25 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.nms.aH.aN.ad(SourceFile:44)
[16:03:25 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.main.ah.ad(SourceFile:36)
[16:03:25 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.Main.onEnable(SourceFile:40)
[16:03:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:03:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
[16:03:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
[16:03:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624)
[16:03:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538)
[16:03:25 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
[16:03:25 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
[16:03:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:338)
[16:03:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[16:03:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[16:03:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:03:25 INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.0.5
[16:03:25 ERROR]: Error occurred while enabling CosmeticsCore v1.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/lone/cosmeticscore/nms/aF/aF
        at dev.lone.cosmeticscore.main.ah.ad(SourceFile:37) ~[CosmeticsCore_1.0.5.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:40) ~[CosmeticsCore_1.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.lone.cosmeticscore.nms.aF.aF
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[16:03:25 INFO]: [CrateReloadedNPC] Enabling CrateReloadedNPC v1.1.0*
[16:03:26 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[16:03:26 INFO]: Running delayed init tasks
[16:03:26 INFO]: [TheCore] Checking for update...
[16:03:26 INFO]: [ProfileStorage] Checking for update...
[16:03:26 INFO]: [InventoryRollbackPlus] Checking for updates...
[16:03:26 WARN]: [FastAsyncWorldEdit] Loaded class com.sk89q.worldguard.protection.association.RegionAssociable from WorldGuard v7.0.8-beta-01+cbb2ba7 which is not a depend or softdepend of this plugin.
[16:03:26 INFO]: [Essentials] Fetching version information...
[16:03:26 INFO]: [com.fastasyncworldedit.bukkit.regions.WorldGuardFeature] Plugin 'WorldGuard' found. Using it now.
[16:03:26 INFO]: [com.fastasyncworldedit.bukkit.FaweBukkit] Attempting to use plugin 'WorldGuard'
[16:03:26 INFO]: [com.fastasyncworldedit.bukkit.regions.GriefPreventionFeature] Plugin 'GriefPrevention' found. Using it now.
[16:03:26 INFO]: [com.fastasyncworldedit.bukkit.FaweBukkit] Attempting to use plugin 'GriefPrevention'
[16:03:26 INFO]: [DecentHolograms] Loading holograms... 
[16:03:27 INFO]: [DecentHolograms] Loaded 9 holograms!
[16:03:27 INFO]: [Vault] Checking for Updates ... 
[16:03:27 INFO]: [AntiFarm] Checking update...
[16:03:27 INFO]: [AntiFarm] There is not a new update available.
[16:03:27 WARN]: [PlaceholderAPI] Loaded class org.json.CDL from OreRegenerator v2.0.5-BETA which is not a depend or softdepend of this plugin.
[16:03:27 INFO]: [BlockProt] BlockProt is up to date. (1.1.7)
[16:03:27 INFO]: [EliteMobs] Latest public release is 8.3.4
[16:03:27 INFO]: [EliteMobs] Your version is 8.3.4
[16:03:27 INFO]: [Duels] No updates were available. You are on the latest version!
[16:03:27 INFO]: [Vault] No new version available
[16:03:27 INFO]: [InventoryRollbackPlus] You are running the latest version.
[16:03:27 INFO]: [BetterStructures] Latest public release is 1.3.5
[16:03:27 INFO]: [BetterStructures] Your version is 1.3.5
[16:03:27 INFO]: [EliteMobs] You are running the latest version!
[16:03:27 INFO]: [BetterStructures] You are running the latest version!
[16:03:27 WARN]: [PlaceholderAPI] Loaded class net.milkbowl.vault.Vault from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
[16:03:27 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[16:03:27 INFO]: [AuctionHouse] Registered Service Provider Essentials for Vault's Economy API
[16:03:27 INFO]: [AuctionHouse] Registered Service Provider LuckPerms for Vault's Chat API
[16:03:27 INFO]: [ItemsAdder] [License] Spigot product licensed to: Jackboi (656902)
[16:03:27 INFO]: [CoreProtect] WorldEdit logging successfully initialized.
[16:03:27 INFO]: [TheCore]   You are using the latest version.
[16:03:27 INFO]: [ProfileStorage]   You are using the latest version.
[16:03:27 INFO]: [QuickShop] Registering bStats metrics...
[16:03:27 INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[16:03:27 INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[16:03:27 INFO]: [ajParkour] You are up to date! (2.12.10)
[16:03:27 INFO]: [Jobs] Successfully linked with Vault.
[16:03:28 INFO]: [Citizens] Loaded 13 NPCs.
[16:03:28 INFO]: [CrateReloaded] Citizens Hook
[16:03:28 INFO]: [QuickShop] Using economy system: EssentialsX Economy
[16:03:28 WARN]: [PlaceholderAPI] Loaded class com.artemis.the.gr8.playerstats.api.PlayerStats from PlayerStats v1.7.2 which is not a depend or softdepend of this plugin.
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: playerstats [1.2.0]
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.3]
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: statistic [2.0.1]
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: mcmmo [1.0]
[16:03:28 WARN]: [PlaceholderAPI] Loaded class com.gmail.nossr50.mcMMO from mcMMO v2.1.217 which is not a depend or softdepend of this plugin.
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: mcmmo [1.0]
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: vault [1.7.1]
[16:03:28 WARN]: [PlaceholderAPI] Loaded class net.buycraft.plugin.bukkit.BuycraftPlugin from BuycraftX v12.0.8 which is not a depend or softdepend of this plugin.
[16:03:28 INFO]: [BuycraftAPI] Successfully connected to bstats
[16:03:28 INFO]: [BuycraftAPI] Successfully hooked into Vault for BuyCraftAPI v4.1
[16:03:28 INFO]: [BuycraftAPI] Loading API Tasks...
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: buycraftAPI [4.1]
[16:03:28 INFO]: 6 placeholder hook(s) registered! 1 placeholder hook(s) have an update available.
[16:03:28 INFO]: [AuctionHouse] Found PlaceholderAPI plugin
[16:03:28 INFO]: [PlaceholderAPI] Successfully registered expansion: auctionhouse [3.3.2]
[16:03:28 INFO]: [AuctionHouse] Registered PlaceholderAPI placeholders
[16:03:28 INFO]: Done (88.143s)! Your server is now online! Write help for more commands.
[16:03:28 INFO]: Stopping server
[16:03:28 INFO]: [CrateReloadedNPC] Disabling CrateReloadedNPC v1.1.0
[16:03:28 INFO]: [CrateReloaded] Disabling CrateReloaded v2.1.14
[16:03:28 INFO]: [Jobs] Disabling Jobs v5.1.1.1
[16:03:28 INFO]: ------------- Jobs -------------
[16:03:28 INFO]: Database save task shutdown!
[16:03:28 INFO]: Buffered payment thread shutdown.
[16:03:28 INFO]: ------------------------------------
[16:03:28 INFO]: [CMILib] Disabling CMILib v1.2.4.1
[16:03:28 INFO]: [MarriageMaster] Disabling MarriageMaster v2.6.8-Release
[16:03:28 INFO]: [MarriageMaster] PlaceholderAPI hook was successfully unregistered!
[16:03:28 INFO]: [MarriageMaster] Cleaning database cache.
[16:03:28 INFO]: [MarriageMaster] Database cache cleaned.
[16:03:28 INFO]: [at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.HikariDataSource] MarriageMaster-Connection-Pool - Shutdown initiated...
[16:03:28 INFO]: [at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.HikariDataSource] MarriageMaster-Connection-Pool - Shutdown completed.
[16:03:28 INFO]: [MarriageMaster]  Marriage Master has been disabled.  :( 
[16:03:28 INFO]: [GSit] Disabling GSit v1.3.0
[16:03:28 INFO]: [GSit] The plugin was successfully disabled.
[16:03:28 INFO]: [Duels] Disabling Duels v3.5.2
[16:03:28 INFO]: [Duels] ExtensionManager: Extension 'Placeholders' is now disabled.
[16:03:28 INFO]: [Duels] Disable process took 10ms.
[16:03:28 INFO]: [Quests] Disabling Quests v4.6.1-b373
[16:03:28 INFO]: [Quests] Saving Quester data...
[16:03:28 INFO]: [Quests] Closing storage...
[16:03:28 INFO]: [Spartan] Disabling Spartan vPhase 490
[16:03:28 INFO]: [QuickShop] Unregistering Spartan compatibility module
[16:03:28 INFO]: [ItemsAdder] Disabling ItemsAdder v3.3.0b-r2
[16:03:29 INFO]: [ItemsAdder] [Host] Started self-host webserver on port: 25722
[16:03:29 INFO]: [QuickShop] Disabling QuickShop v5.1.1.1
[16:03:29 INFO]: [QuickShop] QuickShop is finishing remaining work, this may need a while...
[16:03:29 INFO]: [QuickShop] Unregistering AdvancedShopRegionMarket integration
[16:03:29 INFO]: [QuickShop] Please wait for the data to flush its data...
[16:03:29 INFO]: [VillagerMarket] Disabling VillagerMarket v1.11.4
[16:03:29 INFO]: [BuycraftAPI] Successfully loaded payments
[16:03:29 INFO]: [Rankup] Disabling Rankup v3.13.3
[16:03:29 INFO]: [AdvancedRegionMarket] Disabling AdvancedRegionMarket v3.4.3
[16:03:29 INFO]: [SlotMachine] Disabling SlotMachine v6.5.9
[16:03:29 INFO]: [SlotMachine] Removing old backup
[16:03:29 INFO]: [SlotMachine] Creating a backup of /machines to /machinesLastBackup
[16:03:29 INFO]: [BlockProt] Disabling BlockProt v1.1.7
[16:03:29 INFO]: [BlockProt] Saving statistic file...
[16:03:29 INFO]: [EliteMobs] Disabling EliteMobs v8.3.4
[16:03:29 INFO]: [EliteMobs] Starting EliteMobs shutdown sequence...
[16:03:29 INFO]: [EliteMobs] Regenerating exploded blocks...
[16:03:29 INFO]: [EliteMobs] Cancelling tasks...
[16:03:29 INFO]: [EliteMobs] Closing wormholes...
[16:03:29 INFO]: [EliteMobs] Spinning Regional Bosses down...
[16:03:29 INFO]: [EliteMobs] Wiping Elite entities clean...
[16:03:29 INFO]: [EliteMobs] Clearing events...
[16:03:29 INFO]: [EliteMobs] Clearing valid worlds...
[16:03:29 INFO]: [EliteMobs] Clearing zone based worlds...
[16:03:29 INFO]: [EliteMobs] Clearing config regional elites...
[16:03:29 INFO]: [EliteMobs] Clearing custom enchantments...
[16:03:29 INFO]: [EliteMobs] Clearing custom items...
[16:03:29 INFO]: [EliteMobs] Clearing Minidungeons...
[16:03:29 INFO]: [EliteMobs] Unregistering placeholders...
[16:03:29 INFO]: [EliteMobs] Unregistering handlers...
[16:03:29 INFO]: [EliteMobs] Clearing Treasure Chests...
[16:03:29 INFO]: [EliteMobs] Untracking quests...
[16:03:29 INFO]: [EliteMobs] Saving EliteMobs databases...
[16:03:29 INFO]: [EliteMobs] All done! Good night.
[16:03:29 INFO]: [GriefPrevention] Disabling GriefPrevention v16.18
[16:03:29 INFO]: [GriefPrevention] GriefPrevention disabled.
[16:03:29 INFO]: [mcMMO] Disabling mcMMO v2.1.217
[16:03:29 INFO]: [PlaceholderAPI] Unregistered placeholder expansion mcmmo
[16:03:29 INFO]: [PlaceholderAPI] Reason: required plugin mcMMO was disabled.
[16:03:29 INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[16:03:29 INFO]: [Citizens] Disabling Citizens v2.0.30-SNAPSHOT (build 2846)
[16:03:29 INFO]: [ajAntiXray] Disabling ajAntiXray v2.0.3
[16:03:29 INFO]: ajAntiXray v2.0.3 made by ajgeiss0702 has been disabled!
[16:03:29 INFO]: [ChunkyBorder] Disabling ChunkyBorder v1.1.42
[16:03:29 INFO]: [EssentialsDiscord] Disabling EssentialsDiscord v2.20.0-dev+35-0936fe8
[16:03:29 INFO]: [PyroFishingPro] Disabling PyroFishingPro v4.8.9
[16:03:29 INFO]: [Guilds] Disabling Guilds v3.5.6.6
[16:03:29 INFO]: [Guilds] Shutting down database...
[16:03:29 INFO]: [Guilds] Database has been shut down.
[16:03:29 INFO]: [DecentHolograms] Disabling DecentHolograms v2.7.9
[16:03:29 INFO]: [BetterStructures] Disabling BetterStructures v1.3.5
[16:03:29 INFO]: [BetterStructures] Shutdown!
[16:03:29 INFO]: [WorldGuardExtraFlags] Disabling WorldGuardExtraFlags v4.2.1
[16:03:29 INFO]: [CoreProtect] Disabling CoreProtect v21.3
[16:03:29 INFO]: [CoreProtect] Finishing up data logging. Please wait...
[16:03:30 INFO]: [CoreProtect] Success! Disabled CoreProtect v21.3
[16:03:30 INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.20.0-dev+35-0936fe8
[16:03:30 INFO]: [antiRedstoneClock] Disabling antiRedstoneClock v1.5.0
[16:03:30 INFO]: [AuctionHouse] Disabling AuctionHouse v3.3.2
[16:03:30 INFO]: [PlaceholderAPI] Unregistered placeholder expansion auctionhouse
[16:03:30 INFO]: [PlaceholderAPI] Reason: required plugin AuctionHouse was disabled.
[16:03:30 INFO]: [AuctionHouse] Saving auctions data
[16:03:30 INFO]: [ajParkour] Disabling ajParkour v2.12.10
[16:03:30 INFO]: [ajParkour] Removing all active players from parkour because the plugin is disabling.
[16:03:30 INFO]: ajParkour v2.12.10 by ajgeiss0702 has been disabled!
[16:03:30 INFO]: [WorldGuard] Disabling WorldGuard v7.0.8-beta-01+cbb2ba7
[16:03:30 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[16:03:30 INFO]: [Chunky] Disabling Chunky v1.3.52
[16:03:30 INFO]: [EssentialsChat] Disabling EssentialsChat v2.20.0-dev+35-0936fe8
[16:03:30 INFO]: [ajLeaderboards] Disabling ajLeaderboards v2.6.3
[16:03:30 INFO]: [ajLeaderboards] Shutting down cache method..
[16:03:30 INFO]: [ajLeaderboards] Cache method shut down
[16:03:30 INFO]: [ajLeaderboards] Killing remaining workers
[16:03:30 INFO]: [ajLeaderboards] Remaining workers killed
[16:03:30 INFO]: [ajLeaderboards] ajLeaderboards v2.6.3 disabled.
[16:03:30 INFO]: [TradeSystem] Disabling TradeSystem v2.1.3
[16:03:30 INFO]:  
[16:03:30 INFO]: __________________________________________________________
[16:03:30 INFO]:  
[16:03:30 INFO]:                        TradeSystem [2.1.3]
[16:03:30 INFO]:  
[16:03:30 INFO]: Status:
[16:03:30 INFO]:  
[16:03:30 INFO]: MC-Version: 1.19.3 (R0.1-SNAPSHOT, Purpur)
[16:03:30 INFO]:  
[16:03:30 INFO]:   > Cancelling all active trades
[16:03:30 INFO]:  
[16:03:30 INFO]: Finished (1ms)
[16:03:30 INFO]:  
[16:03:30 INFO]: __________________________________________________________
[16:03:30 INFO]:  
[16:03:30 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v2.5.1-SNAPSHOT-333;a7c402d
[16:03:30 INFO]: [BKCommonLib] [RegionChangeTracker] Region block changes will no longer be notified from FastAsyncWorldEdit (>= v1.17)
[16:03:30 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[16:03:30 INFO]: [VotingPlugin] Disabling VotingPlugin v6.10.0
[16:03:30 INFO]: [HeadDatabase] Disabling HeadDatabase v4.17.0
[16:03:30 INFO]: [Essentials] Disabling Essentials v2.20.0-dev+35-0936fe8
[16:03:30 INFO]: [Vault] [Economy] Essentials Economy unhooked.
[16:03:30 INFO]: [dynmap] Disabling dynmap v3.5-beta-1-844
[16:03:30 INFO]: [dynmap] Unloaded 11 components.
[16:03:30 INFO]: [dynmap] Stopping map renderer...
[16:03:31 INFO]: [dynmap] Disabled
[16:03:31 INFO]: [ProfileStorage] Disabling ProfileStorage v3.1.0
[16:03:31 INFO]: [ProfileStorage] - - - - - - - - Disabling - - - - - - - -
[16:03:31 INFO]: [ProfileStorage] SQLITE Closing
[16:03:31 INFO]: [ProfileStorage]   Closed
[16:03:31 INFO]: [ProfileStorage] ProfileCache
[16:03:31 INFO]: [ProfileStorage]   Able to store 128 items of ProfileCacheData at the same time
[16:03:31 INFO]: [ProfileStorage] ProfileCache
[16:03:31 INFO]: [ProfileStorage]   Cleared
[16:03:31 INFO]: [ProfileStorage] - - - - - Successfully unloaded - - - - -
[16:03:31 INFO]: [My_Worlds] Disabling My_Worlds v1.19-v2
[16:03:31 INFO]: [My_Worlds] My_Worlds disabled!
[16:03:31 INFO]: [TheCore] Disabling TheCore v1.2.0
[16:03:31 INFO]: [TheCore] - - - - - - - - Disabling - - - - - - - -
[16:03:31 INFO]: [TheCore] - - - - - Successfully unloaded - - - - -
[16:03:31 INFO]: [BKCommonLib] Disabling BKCommonLib v1.19.3-v1-SNAPSHOT
[16:03:31 INFO]: [Vault] Disabling Vault v1.7.3-b131
[16:03:31 INFO]: [PlaceholderAPI] Unregistered placeholder expansion vault
[16:03:31 INFO]: [PlaceholderAPI] Reason: required plugin Vault was disabled.
[16:03:31 INFO]: [PlayerStats] Disabling PlayerStats v1.7.2
[16:03:31 INFO]: [PlaceholderAPI] Unregistered placeholder expansion playerstats
[16:03:31 INFO]: [PlaceholderAPI] Reason: required plugin PlayerStats was disabled.
[16:03:31 INFO]: [PlayerStats] Disabled PlayerStats!
[16:03:31 INFO]: [OreRegenerator] Disabling OreRegenerator v2.0.5-BETA
[16:03:31 INFO]: [ProtocolLib] Disabling ProtocolLib v5.0.0-SNAPSHOT-b608
[16:03:31 INFO]: [LoneLibs] Disabling LoneLibs v1.0.22
[16:03:31 INFO]: [Votifier] Disabling Votifier v2.7.3
[16:03:33 INFO]: [Votifier] Votifier disabled.
[16:03:33 INFO]: [BuycraftX] Disabling BuycraftX v12.0.8
[16:03:33 INFO]: [SD] Disabling StreamingDrops v10.8
[16:03:33 INFO]: [SD] Version 10.8 is disabled!
[16:03:33 INFO]: [spark] Disabling spark v1.10.19
[16:03:33 INFO]: [ChatInjector] Disabling ChatInjector v1.0.3
[16:03:33 INFO]: [LuckPerms] Disabling LuckPerms v5.4.55
[16:03:33 INFO]: [LuckPerms] Starting shutdown process...
[16:03:33 INFO]: [LuckPerms] Closing storage...
[16:03:33 INFO]: [LuckPerms] Goodbye!
[16:03:33 INFO]: [MiniMOTD] Disabling MiniMOTD v2.0.10
[16:03:33 INFO]: [AntiFarm] Disabling AntiFarm v1.7.18
[16:03:33 INFO]: [DeluxeTags] Disabling DeluxeTags v1.8.2-Release
[16:03:33 INFO]: [ChatReaction] Disabling ChatReaction v1.8.0
[16:03:33 INFO]: [PyroLib] Disabling PyroLib v1.2.6
[16:03:33 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.2
[16:03:33 INFO]: [InventoryRollbackPlus] Disabling InventoryRollbackPlus v1.6.8
[16:03:33 INFO]: [InventoryRollbackPlus] Setting shutdown state
[16:03:33 INFO]: [InventoryRollbackPlus] Saving player inventories...
[16:03:33 INFO]: [InventoryRollbackPlus] Done saving player inventories!
[16:03:33 INFO]: [InventoryRollbackPlus] Plugin is disabled!
[16:03:35 INFO]: [HeadDatabase] Successfully loaded 50620 heads!
[16:03:35 WARN]: [HeadDatabase] Plugin HeadDatabase v4.17.0 generated an exception while executing task 74
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at me.arcaniax.hdb.HeadDatabaseManager.submitHead(HeadDatabaseManager.java:604) ~[HeadDatabase-4.17.0 (1).jar:?]
        at me.arcaniax.hdb.HeadDatabaseManager.loadCustomDatabase(HeadDatabaseManager.java:593) ~[HeadDatabase-4.17.0 (1).jar:?]
        at me.arcaniax.hdb.HeadDatabaseManager.loadCustomDatabase(HeadDatabaseManager.java:493) ~[HeadDatabase-4.17.0 (1).jar:?]
        at me.arcaniax.hdb.HeadDatabaseManager.lambda$new$1(HeadDatabaseManager.java:139) ~[HeadDatabase-4.17.0 (1).jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:03:35 INFO]: Saving players
[16:03:35 INFO]: Saving worlds
[16:03:35 INFO]: Saving chunks for level 'ServerLevel[Baren_Main_World]'/minecraft:overworld
[16:03:35 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'Baren_Main_World'
[16:03:35 INFO]: [ChunkHolderManager] Halted chunk system for world 'Baren_Main_World'
[16:03:35 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'Baren_Main_World'
[16:03:35 INFO]: [ChunkHolderManager] Saved 69 block chunks, 69 entity chunks, 0 poi chunks in world 'Baren_Main_World' in 0.58s
[16:03:35 INFO]: ThreadedAnvilChunkStorage (Baren_Main_World): All chunks are saved
[16:03:35 INFO]: Saving chunks for level 'ServerLevel[Baren_Main_World_nether]'/minecraft:the_nether
[16:03:35 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'Baren_Main_World_nether'
[16:03:35 INFO]: [ChunkHolderManager] Halted chunk system for world 'Baren_Main_World_nether'
[16:03:35 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'Baren_Main_World_nether'
[16:03:35 INFO]: [ChunkHolderManager] Saved 45 block chunks, 45 entity chunks, 0 poi chunks in world 'Baren_Main_World_nether' in 0.09s
[16:03:35 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:03:35 INFO]: Saving chunks for level 'ServerLevel[Baren_Main_World_the_end]'/minecraft:the_end
[16:03:35 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'Baren_Main_World_the_end'
[16:03:35 INFO]: [ChunkHolderManager] Halted chunk system for world 'Baren_Main_World_the_end'
[16:03:35 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'Baren_Main_World_the_end'
[16:03:35 INFO]: [ChunkHolderManager] Saved 98 block chunks, 98 entity chunks, 0 poi chunks in world 'Baren_Main_World_the_end' in 0.06s
[16:03:35 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:03:35 INFO]: Saving chunks for level 'ServerLevel[em_adventurers_guild]'/minecraft:em_adventurers_guild
[16:03:35 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'em_adventurers_guild'
[16:03:35 INFO]: [ChunkHolderManager] Halted chunk system for world 'em_adventurers_guild'
[16:03:35 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'em_adventurers_guild'
[16:03:36 INFO]: [ChunkHolderManager] Saved 32 block chunks, 32 entity chunks, 0 poi chunks in world 'em_adventurers_guild' in 0.07s
[16:03:36 INFO]: ThreadedAnvilChunkStorage (em_adventurers_guild): All chunks are saved
[16:03:36 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[16:03:36 INFO]: Flushing Chunk IO
[16:03:36 INFO]: Closing Thread Pool
[16:03:36 INFO]: Closing Server
[TideoCP]: Server is offline.
[TideoCP]:  ---------- Detected server process in a crashed state! ----------
[TideoCP]:  Exit code: 0
[TideoCP]:  Out of memory: false
[TideoCP]:  Updating process files
[TideoCP]:  Doing some more tech work...

### Error (optional)

```shell
[15:40:07 INFO]: [CosmeticsCore] Enabling CosmeticsCore v1.0.5
[15:40:07 ERROR]: [CosmeticsCore] Error getting implementation for class dev.lone.cosmeticscore.nms.aH.aN - NMS v1_19_R2
[15:40:07 WARN]: java.lang.ClassNotFoundException: dev.lone.cosmeticscore.nms.aH.impl.v1_19_R2
[15:40:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179)
[15:40:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126)
[15:40:07 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:40:07 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[15:40:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[15:40:07 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.main.ah.a(SourceFile:126)
[15:40:07 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.nms.aH.aN.<init>(SourceFile:29)
[15:40:07 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.nms.aH.aN.ad(SourceFile:44)
[15:40:07 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.main.ah.ad(SourceFile:36)
[15:40:07 WARN]:        at CosmeticsCore_1.0.5.jar//dev.lone.cosmeticscore.Main.onEnable(SourceFile:40)
[15:40:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:40:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
[15:40:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
[15:40:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624)
[15:40:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538)
[15:40:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
[15:40:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
[15:40:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:338)
[15:40:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[15:40:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[15:40:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:40:07 INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.0.5
[15:40:07 ERROR]: Error occurred while enabling CosmeticsCore v1.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/lone/cosmeticscore/nms/aF/aF
        at dev.lone.cosmeticscore.main.ah.ad(SourceFile:37) ~[CosmeticsCore_1.0.5.jar:?]
        at dev.lone.cosmeticscore.Main.onEnable(SourceFile:40) ~[CosmeticsCore_1.0.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.lone.cosmeticscore.nms.aF.aF
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 1
    balloon: 1
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: Baren_Main_World
      x: -77404.5301662641
      y: 184.12000000476837
      z: -41133.50488874611
      yaw: -89.99667
      pitch: 0.7502509
  mannequin:
    location:
      world: Baren_Main_World
      x: -77401.62881992912
      y: 182.0
      z: -41135.492209731936
      yaw: 77.042625
      pitch: -1.0377787
  teleport_area:
    enter:
      world: Baren_Main_World
      pos1:
        x: -77408.0
        y: 182.0
        z: -41139.0
      pos2:
        x: -77408.0
        y: 188.0
        z: -41131.0
    exit_location:
      world: Baren_Main_World
      x: -77409.57268547842
      y: 182.0
      z: -41134.47055239188
      yaw: 90.885956
      pitch: -1.4386057
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![cosmeticsfejl1](https://user-images.githubusercontent.com/121448280/209565942-c379f422-6224-4619-a420-4716b79c1e9d.png)
![cosmeticsfejl](https://user-images.githubusercontent.com/121448280/209565944-85bb505f-59f0-477f-a101-d6b86f9cae64.png)

**Comment by LoneDev6** [comment]
It's not updated to 1.19.3.
It will on Jan 2023.

Il Lun 26 Dic 2022, 17:07 Jackboittv ***@***.***> ha scritto:

**Comment by Jackboittv** [comment]
> 

Yeah okay.. Just didn't expect it to crash the entire server because it doesn't support 1.19.3 :P
(I just removed cosmeticscore, and the server instantly started normally)

**Comment by Jackboittv** [comment]
I love the plugin, but I guess I'll just have to wait before using it again.. :(

**Comment by LoneDev6** [comment]
Fixed in the latest update, thanks

**Comment by luizsusin** [comment]
@LoneDev6 I'm still having issues on 1.19.3. I'll create a new Issue if needed, but I'm using the very same version of the ProtocolLib and LoneLibs as @Jackboittv. It happens when I join the Wardrobe.

Although TAB and ModelEngine are shown in the stacktrace., might be a conflict with CosmeticsCore.

```
[00:30:58 ERROR]: Packet encoding of packet ID 78 threw (skippable? false)
java.lang.ClassCastException: class net.minecraft.network.syncher.DataWatcher$Item cannot be cast to class net.minecraft.network.syncher.DataWatcher$b (net.minecraft.network.syncher.DataWatcher$Item and net.minecraft.network.syncher.DataWatcher$b are in unnamed module of loader java.net.URLClassLoader @11028347)
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:17) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[purpur-1.19.3.jar:git-Purpur-1886]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:93) ~[TAB-3.2.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at com.ticxo.modelengine.nms.v1_19_R2.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:71) ~[Model-Engine-R3.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib-b608.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-b608.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib-b608.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
This is strange as I tested it and works fine on latest 1.19.3.
Try to remove the other plugins, is the golden rule of testing..
